package org.fbi.fskfq.repository.model;

import java.util.ArrayList;
import java.util.List;

public class FsKfqSysCtlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public FsKfqSysCtlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNull() {
            addCriterion("SEQ_NO is null");
            return (Criteria) this;
        }

        public Criteria andSeqNoIsNotNull() {
            addCriterion("SEQ_NO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqNoEqualTo(String value) {
            addCriterion("SEQ_NO =", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotEqualTo(String value) {
            addCriterion("SEQ_NO <>", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThan(String value) {
            addCriterion("SEQ_NO >", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoGreaterThanOrEqualTo(String value) {
            addCriterion("SEQ_NO >=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThan(String value) {
            addCriterion("SEQ_NO <", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLessThanOrEqualTo(String value) {
            addCriterion("SEQ_NO <=", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoLike(String value) {
            addCriterion("SEQ_NO like", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotLike(String value) {
            addCriterion("SEQ_NO not like", value, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoIn(List<String> values) {
            addCriterion("SEQ_NO in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotIn(List<String> values) {
            addCriterion("SEQ_NO not in", values, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoBetween(String value1, String value2) {
            addCriterion("SEQ_NO between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andSeqNoNotBetween(String value1, String value2) {
            addCriterion("SEQ_NO not between", value1, value2, "seqNo");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNull() {
            addCriterion("BANK_ID is null");
            return (Criteria) this;
        }

        public Criteria andBankIdIsNotNull() {
            addCriterion("BANK_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBankIdEqualTo(String value) {
            addCriterion("BANK_ID =", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotEqualTo(String value) {
            addCriterion("BANK_ID <>", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThan(String value) {
            addCriterion("BANK_ID >", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_ID >=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThan(String value) {
            addCriterion("BANK_ID <", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLessThanOrEqualTo(String value) {
            addCriterion("BANK_ID <=", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdLike(String value) {
            addCriterion("BANK_ID like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotLike(String value) {
            addCriterion("BANK_ID not like", value, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdIn(List<String> values) {
            addCriterion("BANK_ID in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotIn(List<String> values) {
            addCriterion("BANK_ID not in", values, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdBetween(String value1, String value2) {
            addCriterion("BANK_ID between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankIdNotBetween(String value1, String value2) {
            addCriterion("BANK_ID not between", value1, value2, "bankId");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("BANK_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("BANK_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("BANK_NAME =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("BANK_NAME <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("BANK_NAME >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("BANK_NAME >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("BANK_NAME <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("BANK_NAME <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("BANK_NAME like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("BANK_NAME not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("BANK_NAME in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("BANK_NAME not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("BANK_NAME between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("BANK_NAME not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andSrcCodeIsNull() {
            addCriterion("SRC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSrcCodeIsNotNull() {
            addCriterion("SRC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSrcCodeEqualTo(String value) {
            addCriterion("SRC_CODE =", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeNotEqualTo(String value) {
            addCriterion("SRC_CODE <>", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeGreaterThan(String value) {
            addCriterion("SRC_CODE >", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SRC_CODE >=", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeLessThan(String value) {
            addCriterion("SRC_CODE <", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeLessThanOrEqualTo(String value) {
            addCriterion("SRC_CODE <=", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeLike(String value) {
            addCriterion("SRC_CODE like", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeNotLike(String value) {
            addCriterion("SRC_CODE not like", value, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeIn(List<String> values) {
            addCriterion("SRC_CODE in", values, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeNotIn(List<String> values) {
            addCriterion("SRC_CODE not in", values, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeBetween(String value1, String value2) {
            addCriterion("SRC_CODE between", value1, value2, "srcCode");
            return (Criteria) this;
        }

        public Criteria andSrcCodeNotBetween(String value1, String value2) {
            addCriterion("SRC_CODE not between", value1, value2, "srcCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeIsNull() {
            addCriterion("DES_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDesCodeIsNotNull() {
            addCriterion("DES_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDesCodeEqualTo(String value) {
            addCriterion("DES_CODE =", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeNotEqualTo(String value) {
            addCriterion("DES_CODE <>", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeGreaterThan(String value) {
            addCriterion("DES_CODE >", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DES_CODE >=", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeLessThan(String value) {
            addCriterion("DES_CODE <", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeLessThanOrEqualTo(String value) {
            addCriterion("DES_CODE <=", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeLike(String value) {
            addCriterion("DES_CODE like", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeNotLike(String value) {
            addCriterion("DES_CODE not like", value, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeIn(List<String> values) {
            addCriterion("DES_CODE in", values, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeNotIn(List<String> values) {
            addCriterion("DES_CODE not in", values, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeBetween(String value1, String value2) {
            addCriterion("DES_CODE between", value1, value2, "desCode");
            return (Criteria) this;
        }

        public Criteria andDesCodeNotBetween(String value1, String value2) {
            addCriterion("DES_CODE not between", value1, value2, "desCode");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtIsNull() {
            addCriterion("WSYS_CHK_DT is null");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtIsNotNull() {
            addCriterion("WSYS_CHK_DT is not null");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtEqualTo(String value) {
            addCriterion("WSYS_CHK_DT =", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtNotEqualTo(String value) {
            addCriterion("WSYS_CHK_DT <>", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtGreaterThan(String value) {
            addCriterion("WSYS_CHK_DT >", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtGreaterThanOrEqualTo(String value) {
            addCriterion("WSYS_CHK_DT >=", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtLessThan(String value) {
            addCriterion("WSYS_CHK_DT <", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtLessThanOrEqualTo(String value) {
            addCriterion("WSYS_CHK_DT <=", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtLike(String value) {
            addCriterion("WSYS_CHK_DT like", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtNotLike(String value) {
            addCriterion("WSYS_CHK_DT not like", value, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtIn(List<String> values) {
            addCriterion("WSYS_CHK_DT in", values, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtNotIn(List<String> values) {
            addCriterion("WSYS_CHK_DT not in", values, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtBetween(String value1, String value2) {
            addCriterion("WSYS_CHK_DT between", value1, value2, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkDtNotBetween(String value1, String value2) {
            addCriterion("WSYS_CHK_DT not between", value1, value2, "wsysChkDt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtIsNull() {
            addCriterion("WSYS_CHK_RT is null");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtIsNotNull() {
            addCriterion("WSYS_CHK_RT is not null");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtEqualTo(String value) {
            addCriterion("WSYS_CHK_RT =", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtNotEqualTo(String value) {
            addCriterion("WSYS_CHK_RT <>", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtGreaterThan(String value) {
            addCriterion("WSYS_CHK_RT >", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtGreaterThanOrEqualTo(String value) {
            addCriterion("WSYS_CHK_RT >=", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtLessThan(String value) {
            addCriterion("WSYS_CHK_RT <", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtLessThanOrEqualTo(String value) {
            addCriterion("WSYS_CHK_RT <=", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtLike(String value) {
            addCriterion("WSYS_CHK_RT like", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtNotLike(String value) {
            addCriterion("WSYS_CHK_RT not like", value, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtIn(List<String> values) {
            addCriterion("WSYS_CHK_RT in", values, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtNotIn(List<String> values) {
            addCriterion("WSYS_CHK_RT not in", values, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtBetween(String value1, String value2) {
            addCriterion("WSYS_CHK_RT between", value1, value2, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andWsysChkRtNotBetween(String value1, String value2) {
            addCriterion("WSYS_CHK_RT not between", value1, value2, "wsysChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtIsNull() {
            addCriterion("HOST_CHK_DT is null");
            return (Criteria) this;
        }

        public Criteria andHostChkDtIsNotNull() {
            addCriterion("HOST_CHK_DT is not null");
            return (Criteria) this;
        }

        public Criteria andHostChkDtEqualTo(String value) {
            addCriterion("HOST_CHK_DT =", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtNotEqualTo(String value) {
            addCriterion("HOST_CHK_DT <>", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtGreaterThan(String value) {
            addCriterion("HOST_CHK_DT >", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtGreaterThanOrEqualTo(String value) {
            addCriterion("HOST_CHK_DT >=", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtLessThan(String value) {
            addCriterion("HOST_CHK_DT <", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtLessThanOrEqualTo(String value) {
            addCriterion("HOST_CHK_DT <=", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtLike(String value) {
            addCriterion("HOST_CHK_DT like", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtNotLike(String value) {
            addCriterion("HOST_CHK_DT not like", value, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtIn(List<String> values) {
            addCriterion("HOST_CHK_DT in", values, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtNotIn(List<String> values) {
            addCriterion("HOST_CHK_DT not in", values, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtBetween(String value1, String value2) {
            addCriterion("HOST_CHK_DT between", value1, value2, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkDtNotBetween(String value1, String value2) {
            addCriterion("HOST_CHK_DT not between", value1, value2, "hostChkDt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtIsNull() {
            addCriterion("HOST_CHK_RT is null");
            return (Criteria) this;
        }

        public Criteria andHostChkRtIsNotNull() {
            addCriterion("HOST_CHK_RT is not null");
            return (Criteria) this;
        }

        public Criteria andHostChkRtEqualTo(String value) {
            addCriterion("HOST_CHK_RT =", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtNotEqualTo(String value) {
            addCriterion("HOST_CHK_RT <>", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtGreaterThan(String value) {
            addCriterion("HOST_CHK_RT >", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtGreaterThanOrEqualTo(String value) {
            addCriterion("HOST_CHK_RT >=", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtLessThan(String value) {
            addCriterion("HOST_CHK_RT <", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtLessThanOrEqualTo(String value) {
            addCriterion("HOST_CHK_RT <=", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtLike(String value) {
            addCriterion("HOST_CHK_RT like", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtNotLike(String value) {
            addCriterion("HOST_CHK_RT not like", value, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtIn(List<String> values) {
            addCriterion("HOST_CHK_RT in", values, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtNotIn(List<String> values) {
            addCriterion("HOST_CHK_RT not in", values, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtBetween(String value1, String value2) {
            addCriterion("HOST_CHK_RT between", value1, value2, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andHostChkRtNotBetween(String value1, String value2) {
            addCriterion("HOST_CHK_RT not between", value1, value2, "hostChkRt");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIsNull() {
            addCriterion("AUTH_CODE is null");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIsNotNull() {
            addCriterion("AUTH_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andAuthCodeEqualTo(String value) {
            addCriterion("AUTH_CODE =", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotEqualTo(String value) {
            addCriterion("AUTH_CODE <>", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeGreaterThan(String value) {
            addCriterion("AUTH_CODE >", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeGreaterThanOrEqualTo(String value) {
            addCriterion("AUTH_CODE >=", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLessThan(String value) {
            addCriterion("AUTH_CODE <", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLessThanOrEqualTo(String value) {
            addCriterion("AUTH_CODE <=", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeLike(String value) {
            addCriterion("AUTH_CODE like", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotLike(String value) {
            addCriterion("AUTH_CODE not like", value, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeIn(List<String> values) {
            addCriterion("AUTH_CODE in", values, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotIn(List<String> values) {
            addCriterion("AUTH_CODE not in", values, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeBetween(String value1, String value2) {
            addCriterion("AUTH_CODE between", value1, value2, "authCode");
            return (Criteria) this;
        }

        public Criteria andAuthCodeNotBetween(String value1, String value2) {
            addCriterion("AUTH_CODE not between", value1, value2, "authCode");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andEditionNumIsNull() {
            addCriterion("EDITION_NUM is null");
            return (Criteria) this;
        }

        public Criteria andEditionNumIsNotNull() {
            addCriterion("EDITION_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andEditionNumEqualTo(Long value) {
            addCriterion("EDITION_NUM =", value, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumNotEqualTo(Long value) {
            addCriterion("EDITION_NUM <>", value, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumGreaterThan(Long value) {
            addCriterion("EDITION_NUM >", value, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumGreaterThanOrEqualTo(Long value) {
            addCriterion("EDITION_NUM >=", value, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumLessThan(Long value) {
            addCriterion("EDITION_NUM <", value, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumLessThanOrEqualTo(Long value) {
            addCriterion("EDITION_NUM <=", value, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumIn(List<Long> values) {
            addCriterion("EDITION_NUM in", values, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumNotIn(List<Long> values) {
            addCriterion("EDITION_NUM not in", values, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumBetween(Long value1, Long value2) {
            addCriterion("EDITION_NUM between", value1, value2, "editionNum");
            return (Criteria) this;
        }

        public Criteria andEditionNumNotBetween(Long value1, Long value2) {
            addCriterion("EDITION_NUM not between", value1, value2, "editionNum");
            return (Criteria) this;
        }

        public Criteria andIsSignIsNull() {
            addCriterion("IS_SIGN is null");
            return (Criteria) this;
        }

        public Criteria andIsSignIsNotNull() {
            addCriterion("IS_SIGN is not null");
            return (Criteria) this;
        }

        public Criteria andIsSignEqualTo(String value) {
            addCriterion("IS_SIGN =", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignNotEqualTo(String value) {
            addCriterion("IS_SIGN <>", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignGreaterThan(String value) {
            addCriterion("IS_SIGN >", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignGreaterThanOrEqualTo(String value) {
            addCriterion("IS_SIGN >=", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignLessThan(String value) {
            addCriterion("IS_SIGN <", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignLessThanOrEqualTo(String value) {
            addCriterion("IS_SIGN <=", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignLike(String value) {
            addCriterion("IS_SIGN like", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignNotLike(String value) {
            addCriterion("IS_SIGN not like", value, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignIn(List<String> values) {
            addCriterion("IS_SIGN in", values, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignNotIn(List<String> values) {
            addCriterion("IS_SIGN not in", values, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignBetween(String value1, String value2) {
            addCriterion("IS_SIGN between", value1, value2, "isSign");
            return (Criteria) this;
        }

        public Criteria andIsSignNotBetween(String value1, String value2) {
            addCriterion("IS_SIGN not between", value1, value2, "isSign");
            return (Criteria) this;
        }

        public Criteria andAuthLenIsNull() {
            addCriterion("AUTH_LEN is null");
            return (Criteria) this;
        }

        public Criteria andAuthLenIsNotNull() {
            addCriterion("AUTH_LEN is not null");
            return (Criteria) this;
        }

        public Criteria andAuthLenEqualTo(String value) {
            addCriterion("AUTH_LEN =", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenNotEqualTo(String value) {
            addCriterion("AUTH_LEN <>", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenGreaterThan(String value) {
            addCriterion("AUTH_LEN >", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenGreaterThanOrEqualTo(String value) {
            addCriterion("AUTH_LEN >=", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenLessThan(String value) {
            addCriterion("AUTH_LEN <", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenLessThanOrEqualTo(String value) {
            addCriterion("AUTH_LEN <=", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenLike(String value) {
            addCriterion("AUTH_LEN like", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenNotLike(String value) {
            addCriterion("AUTH_LEN not like", value, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenIn(List<String> values) {
            addCriterion("AUTH_LEN in", values, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenNotIn(List<String> values) {
            addCriterion("AUTH_LEN not in", values, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenBetween(String value1, String value2) {
            addCriterion("AUTH_LEN between", value1, value2, "authLen");
            return (Criteria) this;
        }

        public Criteria andAuthLenNotBetween(String value1, String value2) {
            addCriterion("AUTH_LEN not between", value1, value2, "authLen");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 06 16:49:52 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}