package org.fbi.fskfq.repository.model;

import java.math.BigDecimal;

public class FsKfqPaymentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String chrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String billtypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String billtypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String makedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String ienCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String ienName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String consignIenCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String consignIenName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String pmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String pmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String chequeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String payerbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String payeraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String receiverbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String receiveraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String verifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String rgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String receivetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String inputername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String isConsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String lateflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String nosourceIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String supplytempletId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String bankIndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String incomestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String setYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String routeUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private BigDecimal billMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String bankUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String canceldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String hostBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String hostChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String fbBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String fbChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String archiveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operInitBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operInitTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operInitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operInitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operInitHostsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operPayBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operPayTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operPayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operPayHostsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operCancelBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operCancelTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operCancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operCancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operCancelHostsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operArchiveBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operArchiveTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operArchiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String operArchiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String hostAckFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String lnkBillStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_INFO.MANUAL_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String manualFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @param pkid the value for FIS.FS_KFQ_PAYMENT_INFO.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getChrId() {
        return chrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @param chrId the value for FIS.FS_KFQ_PAYMENT_INFO.CHR_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setChrId(String chrId) {
        this.chrId = chrId == null ? null : chrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBilltypeCode() {
        return billtypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @param billtypeCode the value for FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBilltypeCode(String billtypeCode) {
        this.billtypeCode = billtypeCode == null ? null : billtypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBilltypeName() {
        return billtypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @param billtypeName the value for FIS.FS_KFQ_PAYMENT_INFO.BILLTYPE_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBilltypeName(String billtypeName) {
        this.billtypeName = billtypeName == null ? null : billtypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @param billNo the value for FIS.FS_KFQ_PAYMENT_INFO.BILL_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @param makedate the value for FIS.FS_KFQ_PAYMENT_INFO.MAKEDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setMakedate(String makedate) {
        this.makedate = makedate == null ? null : makedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getIenCode() {
        return ienCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @param ienCode the value for FIS.FS_KFQ_PAYMENT_INFO.IEN_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setIenCode(String ienCode) {
        this.ienCode = ienCode == null ? null : ienCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getIenName() {
        return ienName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @param ienName the value for FIS.FS_KFQ_PAYMENT_INFO.IEN_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setIenName(String ienName) {
        this.ienName = ienName == null ? null : ienName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getConsignIenCode() {
        return consignIenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @param consignIenCode the value for FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setConsignIenCode(String consignIenCode) {
        this.consignIenCode = consignIenCode == null ? null : consignIenCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getConsignIenName() {
        return consignIenName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @param consignIenName the value for FIS.FS_KFQ_PAYMENT_INFO.CONSIGN_IEN_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setConsignIenName(String consignIenName) {
        this.consignIenName = consignIenName == null ? null : consignIenName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPmCode() {
        return pmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @param pmCode the value for FIS.FS_KFQ_PAYMENT_INFO.PM_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPmCode(String pmCode) {
        this.pmCode = pmCode == null ? null : pmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPmName() {
        return pmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @param pmName the value for FIS.FS_KFQ_PAYMENT_INFO.PM_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPmName(String pmName) {
        this.pmName = pmName == null ? null : pmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getChequeNo() {
        return chequeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @param chequeNo the value for FIS.FS_KFQ_PAYMENT_INFO.CHEQUE_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo == null ? null : chequeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @param payer the value for FIS.FS_KFQ_PAYMENT_INFO.PAYER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPayerbank() {
        return payerbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @param payerbank the value for FIS.FS_KFQ_PAYMENT_INFO.PAYERBANK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPayerbank(String payerbank) {
        this.payerbank = payerbank == null ? null : payerbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPayeraccount() {
        return payeraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @param payeraccount the value for FIS.FS_KFQ_PAYMENT_INFO.PAYERACCOUNT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPayeraccount(String payeraccount) {
        this.payeraccount = payeraccount == null ? null : payeraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @param receiver the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getReceiverbank() {
        return receiverbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @param receiverbank the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVERBANK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setReceiverbank(String receiverbank) {
        this.receiverbank = receiverbank == null ? null : receiverbank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getReceiveraccount() {
        return receiveraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @param receiveraccount the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVERACCOUNT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setReceiveraccount(String receiveraccount) {
        this.receiveraccount = receiveraccount == null ? null : receiveraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getVerifyNo() {
        return verifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @param verifyNo the value for FIS.FS_KFQ_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setVerifyNo(String verifyNo) {
        this.verifyNo = verifyNo == null ? null : verifyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getRgCode() {
        return rgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @param rgCode the value for FIS.FS_KFQ_PAYMENT_INFO.RG_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setRgCode(String rgCode) {
        this.rgCode = rgCode == null ? null : rgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getReceivetype() {
        return receivetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @param receivetype the value for FIS.FS_KFQ_PAYMENT_INFO.RECEIVETYPE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setReceivetype(String receivetype) {
        this.receivetype = receivetype == null ? null : receivetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getInputername() {
        return inputername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @param inputername the value for FIS.FS_KFQ_PAYMENT_INFO.INPUTERNAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setInputername(String inputername) {
        this.inputername = inputername == null ? null : inputername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getIsConsign() {
        return isConsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @param isConsign the value for FIS.FS_KFQ_PAYMENT_INFO.IS_CONSIGN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setIsConsign(String isConsign) {
        this.isConsign = isConsign == null ? null : isConsign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getLateflag() {
        return lateflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @param lateflag the value for FIS.FS_KFQ_PAYMENT_INFO.LATEFLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setLateflag(String lateflag) {
        this.lateflag = lateflag == null ? null : lateflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getNosourceIds() {
        return nosourceIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @param nosourceIds the value for FIS.FS_KFQ_PAYMENT_INFO.NOSOURCE_IDS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setNosourceIds(String nosourceIds) {
        this.nosourceIds = nosourceIds == null ? null : nosourceIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getSupplytempletId() {
        return supplytempletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @param supplytempletId the value for FIS.FS_KFQ_PAYMENT_INFO.SUPPLYTEMPLET_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setSupplytempletId(String supplytempletId) {
        this.supplytempletId = supplytempletId == null ? null : supplytempletId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @param remark the value for FIS.FS_KFQ_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBankIndate() {
        return bankIndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @param bankIndate the value for FIS.FS_KFQ_PAYMENT_INFO.BANK_INDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBankIndate(String bankIndate) {
        this.bankIndate = bankIndate == null ? null : bankIndate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getIncomestatus() {
        return incomestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @param incomestatus the value for FIS.FS_KFQ_PAYMENT_INFO.INCOMESTATUS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setIncomestatus(String incomestatus) {
        this.incomestatus = incomestatus == null ? null : incomestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getSetYear() {
        return setYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @param setYear the value for FIS.FS_KFQ_PAYMENT_INFO.SET_YEAR
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setSetYear(String setYear) {
        this.setYear = setYear == null ? null : setYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getRouteUserCode() {
        return routeUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @param routeUserCode the value for FIS.FS_KFQ_PAYMENT_INFO.ROUTE_USER_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setRouteUserCode(String routeUserCode) {
        this.routeUserCode = routeUserCode == null ? null : routeUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @param license the value for FIS.FS_KFQ_PAYMENT_INFO.LICENSE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setLicense(String license) {
        this.license = license == null ? null : license.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @param businessId the value for FIS.FS_KFQ_PAYMENT_INFO.BUSINESS_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBusinessId(String businessId) {
        this.businessId = businessId == null ? null : businessId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public BigDecimal getBillMoney() {
        return billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @param billMoney the value for FIS.FS_KFQ_PAYMENT_INFO.BILL_MONEY
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBillMoney(BigDecimal billMoney) {
        this.billMoney = billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBankUser() {
        return bankUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @param bankUser the value for FIS.FS_KFQ_PAYMENT_INFO.BANK_USER
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBankUser(String bankUser) {
        this.bankUser = bankUser == null ? null : bankUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @param bankNo the value for FIS.FS_KFQ_PAYMENT_INFO.BANK_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getCanceldate() {
        return canceldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @param canceldate the value for FIS.FS_KFQ_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setCanceldate(String canceldate) {
        this.canceldate = canceldate == null ? null : canceldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getHostBookFlag() {
        return hostBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @param hostBookFlag the value for FIS.FS_KFQ_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setHostBookFlag(String hostBookFlag) {
        this.hostBookFlag = hostBookFlag == null ? null : hostBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getHostChkFlag() {
        return hostChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @param hostChkFlag the value for FIS.FS_KFQ_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setHostChkFlag(String hostChkFlag) {
        this.hostChkFlag = hostChkFlag == null ? null : hostChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getFbBookFlag() {
        return fbBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @param fbBookFlag the value for FIS.FS_KFQ_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setFbBookFlag(String fbBookFlag) {
        this.fbBookFlag = fbBookFlag == null ? null : fbBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getFbChkFlag() {
        return fbChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @param fbChkFlag the value for FIS.FS_KFQ_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setFbChkFlag(String fbChkFlag) {
        this.fbChkFlag = fbChkFlag == null ? null : fbChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getArchiveFlag() {
        return archiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @param archiveFlag the value for FIS.FS_KFQ_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setArchiveFlag(String archiveFlag) {
        this.archiveFlag = archiveFlag == null ? null : archiveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperInitBankid() {
        return operInitBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @param operInitBankid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperInitBankid(String operInitBankid) {
        this.operInitBankid = operInitBankid == null ? null : operInitBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperInitTlrid() {
        return operInitTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @param operInitTlrid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperInitTlrid(String operInitTlrid) {
        this.operInitTlrid = operInitTlrid == null ? null : operInitTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperInitDate() {
        return operInitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @param operInitDate the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperInitDate(String operInitDate) {
        this.operInitDate = operInitDate == null ? null : operInitDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperInitTime() {
        return operInitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @param operInitTime the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperInitTime(String operInitTime) {
        this.operInitTime = operInitTime == null ? null : operInitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperInitHostsn() {
        return operInitHostsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @param operInitHostsn the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperInitHostsn(String operInitHostsn) {
        this.operInitHostsn = operInitHostsn == null ? null : operInitHostsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperPayBankid() {
        return operPayBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @param operPayBankid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperPayBankid(String operPayBankid) {
        this.operPayBankid = operPayBankid == null ? null : operPayBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperPayTlrid() {
        return operPayTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @param operPayTlrid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperPayTlrid(String operPayTlrid) {
        this.operPayTlrid = operPayTlrid == null ? null : operPayTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperPayDate() {
        return operPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @param operPayDate the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperPayDate(String operPayDate) {
        this.operPayDate = operPayDate == null ? null : operPayDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperPayTime() {
        return operPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @param operPayTime the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperPayTime(String operPayTime) {
        this.operPayTime = operPayTime == null ? null : operPayTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperPayHostsn() {
        return operPayHostsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @param operPayHostsn the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperPayHostsn(String operPayHostsn) {
        this.operPayHostsn = operPayHostsn == null ? null : operPayHostsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperCancelBankid() {
        return operCancelBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @param operCancelBankid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperCancelBankid(String operCancelBankid) {
        this.operCancelBankid = operCancelBankid == null ? null : operCancelBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperCancelTlrid() {
        return operCancelTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @param operCancelTlrid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperCancelTlrid(String operCancelTlrid) {
        this.operCancelTlrid = operCancelTlrid == null ? null : operCancelTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperCancelDate() {
        return operCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @param operCancelDate the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperCancelDate(String operCancelDate) {
        this.operCancelDate = operCancelDate == null ? null : operCancelDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperCancelTime() {
        return operCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @param operCancelTime the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperCancelTime(String operCancelTime) {
        this.operCancelTime = operCancelTime == null ? null : operCancelTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperCancelHostsn() {
        return operCancelHostsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @param operCancelHostsn the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperCancelHostsn(String operCancelHostsn) {
        this.operCancelHostsn = operCancelHostsn == null ? null : operCancelHostsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperArchiveBankid() {
        return operArchiveBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @param operArchiveBankid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperArchiveBankid(String operArchiveBankid) {
        this.operArchiveBankid = operArchiveBankid == null ? null : operArchiveBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperArchiveTlrid() {
        return operArchiveTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @param operArchiveTlrid the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperArchiveTlrid(String operArchiveTlrid) {
        this.operArchiveTlrid = operArchiveTlrid == null ? null : operArchiveTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperArchiveDate() {
        return operArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @param operArchiveDate the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperArchiveDate(String operArchiveDate) {
        this.operArchiveDate = operArchiveDate == null ? null : operArchiveDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getOperArchiveTime() {
        return operArchiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @param operArchiveTime the value for FIS.FS_KFQ_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setOperArchiveTime(String operArchiveTime) {
        this.operArchiveTime = operArchiveTime == null ? null : operArchiveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_KFQ_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getHostAckFlag() {
        return hostAckFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @param hostAckFlag the value for FIS.FS_KFQ_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setHostAckFlag(String hostAckFlag) {
        this.hostAckFlag = hostAckFlag == null ? null : hostAckFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getLnkBillStatus() {
        return lnkBillStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @param lnkBillStatus the value for FIS.FS_KFQ_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setLnkBillStatus(String lnkBillStatus) {
        this.lnkBillStatus = lnkBillStatus == null ? null : lnkBillStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_INFO.MANUAL_FLAG
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_INFO.MANUAL_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getManualFlag() {
        return manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_INFO.MANUAL_FLAG
     *
     * @param manualFlag the value for FIS.FS_KFQ_PAYMENT_INFO.MANUAL_FLAG
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setManualFlag(String manualFlag) {
        this.manualFlag = manualFlag == null ? null : manualFlag.trim();
    }
}