package org.fbi.fskfq.repository.model;

import java.math.BigDecimal;

public class FsKfqPaymentItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.CHR_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String chrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.MAIN_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String mainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String inBisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String inBisName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.MEASURE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String measure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGENUM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String chargenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGESTANDARD
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String chargestandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGEMONEY
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private BigDecimal chargemoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.ITEM_CHKCODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String itemChkcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_PAYMENT_ITEM.MAIN_PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String mainPkid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.PKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.PKID
     *
     * @param pkid the value for FIS.FS_KFQ_PAYMENT_ITEM.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHR_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.CHR_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getChrId() {
        return chrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHR_ID
     *
     * @param chrId the value for FIS.FS_KFQ_PAYMENT_ITEM.CHR_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setChrId(String chrId) {
        this.chrId = chrId == null ? null : chrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.MAIN_ID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.MAIN_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getMainId() {
        return mainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.MAIN_ID
     *
     * @param mainId the value for FIS.FS_KFQ_PAYMENT_ITEM.MAIN_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setMainId(String mainId) {
        this.mainId = mainId == null ? null : mainId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_CODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getInBisCode() {
        return inBisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_CODE
     *
     * @param inBisCode the value for FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setInBisCode(String inBisCode) {
        this.inBisCode = inBisCode == null ? null : inBisCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_NAME
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getInBisName() {
        return inBisName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_NAME
     *
     * @param inBisName the value for FIS.FS_KFQ_PAYMENT_ITEM.IN_BIS_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setInBisName(String inBisName) {
        this.inBisName = inBisName == null ? null : inBisName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.MEASURE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.MEASURE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getMeasure() {
        return measure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.MEASURE
     *
     * @param measure the value for FIS.FS_KFQ_PAYMENT_ITEM.MEASURE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setMeasure(String measure) {
        this.measure = measure == null ? null : measure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGENUM
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.CHARGENUM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getChargenum() {
        return chargenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGENUM
     *
     * @param chargenum the value for FIS.FS_KFQ_PAYMENT_ITEM.CHARGENUM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setChargenum(String chargenum) {
        this.chargenum = chargenum == null ? null : chargenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGESTANDARD
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.CHARGESTANDARD
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getChargestandard() {
        return chargestandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGESTANDARD
     *
     * @param chargestandard the value for FIS.FS_KFQ_PAYMENT_ITEM.CHARGESTANDARD
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setChargestandard(String chargestandard) {
        this.chargestandard = chargestandard == null ? null : chargestandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGEMONEY
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.CHARGEMONEY
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public BigDecimal getChargemoney() {
        return chargemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.CHARGEMONEY
     *
     * @param chargemoney the value for FIS.FS_KFQ_PAYMENT_ITEM.CHARGEMONEY
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setChargemoney(BigDecimal chargemoney) {
        this.chargemoney = chargemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.ITEM_CHKCODE
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.ITEM_CHKCODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getItemChkcode() {
        return itemChkcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.ITEM_CHKCODE
     *
     * @param itemChkcode the value for FIS.FS_KFQ_PAYMENT_ITEM.ITEM_CHKCODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setItemChkcode(String itemChkcode) {
        this.itemChkcode = itemChkcode == null ? null : itemChkcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.MAIN_PKID
     *
     * @return the value of FIS.FS_KFQ_PAYMENT_ITEM.MAIN_PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getMainPkid() {
        return mainPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_PAYMENT_ITEM.MAIN_PKID
     *
     * @param mainPkid the value for FIS.FS_KFQ_PAYMENT_ITEM.MAIN_PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setMainPkid(String mainPkid) {
        this.mainPkid = mainPkid == null ? null : mainPkid.trim();
    }
}