package org.fbi.fskfq.repository.model;

public class FsKfqSysCtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.SEQ_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.BANK_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.SRC_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String srcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.DES_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String desCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.WSYS_CHK_DT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String wsysChkDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.WSYS_CHK_RT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String wsysChkRt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String hostChkDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.HOST_CHK_RT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String hostChkRt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.AUTH_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String authCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.USER_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.PASSWORD
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.REMARK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.EDITION_NUM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private Long editionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.IS_SIGN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String isSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_KFQ_SYS_CTL.AUTH_LEN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    private String authLen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.PKID
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.PKID
     *
     * @param pkid the value for FIS.FS_KFQ_SYS_CTL.PKID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.SEQ_NO
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.SEQ_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.SEQ_NO
     *
     * @param seqNo the value for FIS.FS_KFQ_SYS_CTL.SEQ_NO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setSeqNo(String seqNo) {
        this.seqNo = seqNo == null ? null : seqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.BANK_ID
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.BANK_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.BANK_ID
     *
     * @param bankId the value for FIS.FS_KFQ_SYS_CTL.BANK_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.BANK_NAME
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.BANK_NAME
     *
     * @param bankName the value for FIS.FS_KFQ_SYS_CTL.BANK_NAME
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.SRC_CODE
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.SRC_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getSrcCode() {
        return srcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.SRC_CODE
     *
     * @param srcCode the value for FIS.FS_KFQ_SYS_CTL.SRC_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setSrcCode(String srcCode) {
        this.srcCode = srcCode == null ? null : srcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.DES_CODE
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.DES_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getDesCode() {
        return desCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.DES_CODE
     *
     * @param desCode the value for FIS.FS_KFQ_SYS_CTL.DES_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setDesCode(String desCode) {
        this.desCode = desCode == null ? null : desCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.WSYS_CHK_DT
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.WSYS_CHK_DT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getWsysChkDt() {
        return wsysChkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.WSYS_CHK_DT
     *
     * @param wsysChkDt the value for FIS.FS_KFQ_SYS_CTL.WSYS_CHK_DT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setWsysChkDt(String wsysChkDt) {
        this.wsysChkDt = wsysChkDt == null ? null : wsysChkDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.WSYS_CHK_RT
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.WSYS_CHK_RT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getWsysChkRt() {
        return wsysChkRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.WSYS_CHK_RT
     *
     * @param wsysChkRt the value for FIS.FS_KFQ_SYS_CTL.WSYS_CHK_RT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setWsysChkRt(String wsysChkRt) {
        this.wsysChkRt = wsysChkRt == null ? null : wsysChkRt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.HOST_CHK_DT
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getHostChkDt() {
        return hostChkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.HOST_CHK_DT
     *
     * @param hostChkDt the value for FIS.FS_KFQ_SYS_CTL.HOST_CHK_DT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setHostChkDt(String hostChkDt) {
        this.hostChkDt = hostChkDt == null ? null : hostChkDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.HOST_CHK_RT
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.HOST_CHK_RT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getHostChkRt() {
        return hostChkRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.HOST_CHK_RT
     *
     * @param hostChkRt the value for FIS.FS_KFQ_SYS_CTL.HOST_CHK_RT
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setHostChkRt(String hostChkRt) {
        this.hostChkRt = hostChkRt == null ? null : hostChkRt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.AUTH_CODE
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.AUTH_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.AUTH_CODE
     *
     * @param authCode the value for FIS.FS_KFQ_SYS_CTL.AUTH_CODE
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode == null ? null : authCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.USER_ID
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.USER_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.USER_ID
     *
     * @param userId the value for FIS.FS_KFQ_SYS_CTL.USER_ID
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.PASSWORD
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.PASSWORD
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.PASSWORD
     *
     * @param password the value for FIS.FS_KFQ_SYS_CTL.PASSWORD
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.REMARK
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.REMARK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.REMARK
     *
     * @param remark the value for FIS.FS_KFQ_SYS_CTL.REMARK
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.EDITION_NUM
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.EDITION_NUM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public Long getEditionNum() {
        return editionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.EDITION_NUM
     *
     * @param editionNum the value for FIS.FS_KFQ_SYS_CTL.EDITION_NUM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setEditionNum(Long editionNum) {
        this.editionNum = editionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.IS_SIGN
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.IS_SIGN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.IS_SIGN
     *
     * @param isSign the value for FIS.FS_KFQ_SYS_CTL.IS_SIGN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setIsSign(String isSign) {
        this.isSign = isSign == null ? null : isSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_KFQ_SYS_CTL.AUTH_LEN
     *
     * @return the value of FIS.FS_KFQ_SYS_CTL.AUTH_LEN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public String getAuthLen() {
        return authLen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_KFQ_SYS_CTL.AUTH_LEN
     *
     * @param authLen the value for FIS.FS_KFQ_SYS_CTL.AUTH_LEN
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    public void setAuthLen(String authLen) {
        this.authLen = authLen == null ? null : authLen.trim();
    }
}