package org.fbi.fskfq.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.fskfq.repository.model.FsKfqPaymentItem;
import org.fbi.fskfq.repository.model.FsKfqPaymentItemExample;

public interface FsKfqPaymentItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int countByExample(FsKfqPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int deleteByExample(FsKfqPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int insert(FsKfqPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int insertSelective(FsKfqPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    List<FsKfqPaymentItem> selectByExample(FsKfqPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    FsKfqPaymentItem selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") FsKfqPaymentItem record, @Param("example") FsKfqPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByExample(@Param("record") FsKfqPaymentItem record, @Param("example") FsKfqPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByPrimaryKeySelective(FsKfqPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_ITEM
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByPrimaryKey(FsKfqPaymentItem record);
}