package org.fbi.fskfq.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.fskfq.repository.model.FsKfqSysCtl;
import org.fbi.fskfq.repository.model.FsKfqSysCtlExample;

public interface FsKfqSysCtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int countByExample(FsKfqSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int deleteByExample(FsKfqSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int insert(FsKfqSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int insertSelective(FsKfqSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    List<FsKfqSysCtl> selectByExample(FsKfqSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    FsKfqSysCtl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") FsKfqSysCtl record, @Param("example") FsKfqSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByExample(@Param("record") FsKfqSysCtl record, @Param("example") FsKfqSysCtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByPrimaryKeySelective(FsKfqSysCtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_SYS_CTL
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByPrimaryKey(FsKfqSysCtl record);
}