package org.fbi.fskfq.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.fskfq.repository.model.FsKfqPaymentInfo;
import org.fbi.fskfq.repository.model.FsKfqPaymentInfoExample;

public interface FsKfqPaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int countByExample(FsKfqPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int deleteByExample(FsKfqPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int insert(FsKfqPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int insertSelective(FsKfqPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    List<FsKfqPaymentInfo> selectByExample(FsKfqPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    FsKfqPaymentInfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") FsKfqPaymentInfo record, @Param("example") FsKfqPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByExample(@Param("record") FsKfqPaymentInfo record, @Param("example") FsKfqPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByPrimaryKeySelective(FsKfqPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_KFQ_PAYMENT_INFO
     *
     * @mbggenerated Mon Jan 06 16:49:52 CST 2014
     */
    int updateByPrimaryKey(FsKfqPaymentInfo record);
}